### ISSUE TITLE
Permit sets with parametric values

### ISSUE THREAD

**Issue by henryx** [cosiner/flag#1]
For example:

`command help set`

If I've understood the library, is not possible to use this syntax

**Comment by cosiner** [comment]
@henryx Thanks for your feedback.

In this example, the library has builtin support for `command -h set` or `command set -h`.
If you still need `command help set`, then write some code like this:
```Go
type Command struct {
	Help struct {
		Enable  bool
		Subsets []string `args:"true" arglist:"[SUBSET]..."`
	}
}

func main() {
	var cmd Command
	cmdline := flag.NewFlagSet(flag.Flag{}).NeedHelpFlag(false)
	cmdline.ParseStruct(&cmd)

	if cmd.Help.Enable {
		subset, err := cmdline.FindSubset(strings.Join(cmd.Help.Subsets, ","))
		if err != nil {
			fmt.Fprintf(os.Stderr, err.Error())
			os.Exit(2)
		}
		subset.Help(false)
		return
	}
}
```

**Comment by henryx** [comment]
Thank you so much, for you work and for your availability
