### ISSUE TITLE
Does this support implied flags, like tar?

### ISSUE THREAD

**Issue by coolaj86** [cosiner/flag#12]
> '-' to ensure next argument must be a flag

That seems to imply that implied flags will work here the same as they do with `tar`:

```bash
tar -xvf test.tar.gz
tar xvf test.tar.gz
```

Is that true?

**Comment by zhuah** [comment]
no, you can just ignore this rule, and this library doesn't supports this syntax `tar xvf test.tar.gz`

**Comment by coolaj86** [comment]
Thanks.
