### ISSUE TITLE
Add support for mandatory flags

### ISSUE THREAD

**Issue by vbatoufflet** [cosiner/flag#2]
Hi,

Maybe I missed something, but I couldn't find a way to declare mandatory settings.

It would be great to have such feature implemented.

Regards

**Comment by cosiner** [comment]
@vbatoufflet Thanks for your feedback and sorry for the late response.

Obviously, it's useless for boolean flag, for other flag type such as string, int, with this feature, you still need to checking legality of flag value. So, I think it's not so useful currently, glad to see your opinion.

**Comment by vbatoufflet** [comment]
@cosiner,

Thanks for your reply.

I guess that's make sense. I'm closing the issue.
