### ISSUE TITLE
How deep can I nest the structs?

### ISSUE THREAD

**Issue by didip** [cosiner/flag#7]
It looks like the 3rd nested structs aren't visible. Example:

```
type Arguments struct {
	Index struct {
		Enable bool

		Full struct {
			Enable bool

			// This is not visible
			List struct {
				Enable bool
			}

			// This is not visible as well
			Syncto struct {
				Enable bool

				Cassandra struct {
					Enable bool
					All    bool `names:"--all" default:"true" desc:"Just sync everything from Redis to Cassandra"`
				}
			}
		}
	}
}
```

This is the error I got:

```
go run -race main.go index full list
StandaloneValue: standalone value without flag: [main index full] list
```

**Comment by cosiner** [comment]
Thanks, this bug has been fixed in the latest commit, and also, the nesting levels is unlimited.

**Comment by didip** [comment]
Confirmed that the latest sha fixed this issue.

Btw, this thing is so awesome. It's significantly less code that kingpin and urfave/cli for moderately complicated CLI application. Thank you for building it. Using struct tags is so brilliant!
