### ISSUE TITLE
Add positional tag

### ISSUE THREAD

**Issue by henryx** [cosiner/flag#9]
Is a good idea add a tag for setting postitional arguments. For example:

```golang
type Args struct {
	Version string `names:"-v" usage:"Version"`
	Pos     string `names:"positional" positional:"true" usage"positional flag"`
}
```
Result would be:
```
Usage:
    cmd [FLAG] [positional]...

Flags:
      -v               Version
      -h, --help   show help

Positional flags:
    positional    positional flag
```

**Comment by cosiner** [comment]
@henryx Sorry, could you show me a more detailed example, i am confused about what 'positional' means. Is it 'optional'?

**Comment by henryx** [comment]
Consider this simple example:
```
cp -a file newfile
```

In some libraries, `-a` is called as flag, and `file` is called as positional argument

**Comment by cosiner** [comment]
In the `cp` example, there is a tag `args` can do this work.
Here is a example of `tar`:
```Go
type Tar struct {
	GZ          bool     `names:"-z, --gz" usage:"gzip format"`
	BZ          bool     `names:"-j, --bz" usage:"bzip2 format"`
	XZ          bool     `names:"-J, --xz" usage:"xz format"`
	Create      bool     `names:"-c" usage:"create tar file"`
	Extract     bool     `names:"-x" usage:"extract tar file"`
	File        string   `names:"-f" usage:"output file for create or input file for extract"`
	Directory   string   `names:"-C" usage:"extract directory"`
	SourceFiles []string `args:"true"`
}
```
The `args` tag is just like `flag.Args()` in Go std library, it will catch all non-flag arguments.

**Comment by henryx** [comment]
I understand, but `args` is usable only for `[]string` type, in my example,
`positional` is usable for all types

2017-08-31 3:35 GMT+02:00 Aihui Zhu <notifications@github.com>:

**Comment by cosiner** [comment]
Sorry for the late response, i'm working for other things.

I will add this to my to-do list, but the time is not sure, so just keep this issue opened.
